version: '3.8'

services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: ganache
    restart: always
    ports:
      - '8545:8545'
