# syntax=docker/dockerfile:1.0.0-experimental
FROM node:20.2.0-bullseye

RUN npm install ganache --global

CMD ["ganache", "--miner.blockTime=2", "--host=0.0.0.0", "--mnemonic=vessel waste salad salon brother rely place hybrid joy predict tourist used"]
